"""new fields in model

Revision ID: 5987df2cc5af
Revises: 937afa315fac
Create Date: 2021-12-08 17:02:19.131307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5987df2cc5af'
down_revision = '937afa315fac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
